import 'dart:convert';
import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:thumbhash_ffi/src/codec/codec_dart.dart' as dart_codec;
import 'package:thumbhash_ffi/src/hash_header.dart';
import 'package:thumbhash_ffi/thumbhash_ffi.dart';

import 'src/matchers.dart';
import 'src/patterns.dart';
import 'src/reference_fixtures.dart';

/// How many hash values may be off by one compared to the fixtures, which
/// were generated by the Rust crate on Linux.
///
/// The native codec is that same crate, but `cosf` differs slightly between
/// platforms. The Dart codec uses double precision and sums in a different
/// order: degenerate images (e.g. 1 pixel wide) have many coefficients that
/// are exactly 0.5 after normalization, where the rounding direction depends
/// on the sign of the floating point error of `cos(pi / 2)`.
const _maxNativeDifferences = 2;
const _maxDartDifferences = 16;

typedef _Codec = ({
  String name,
  int maxHashDifferences,
  Uint8List Function(int width, int height, Uint8List rgba) encode,
  ({int width, int height, Uint8List rgba}) Function(
    Uint8List hash,
    bool premultiplied,
  )
  decode,
});

void main() {
  final codecs = <_Codec>[
    (
      name: ThumbHash.isNative ? 'native codec' : 'web codec',
      maxHashDifferences: ThumbHash.isNative
          ? _maxNativeDifferences
          : _maxDartDifferences,
      encode: (width, height, rgba) =>
          ThumbHash.encodeRgba(width, height, rgba).bytes,
      decode: (hash, premultiplied) {
        final pixels = ThumbHash.fromBytes(
          hash,
        ).toPixels(premultiplied: premultiplied);
        return (width: pixels.width, height: pixels.height, rgba: pixels.rgba);
      },
    ),
    // The Dart port runs on the web; test it everywhere.
    if (ThumbHash.isNative)
      (
        name: 'Dart codec',
        maxHashDifferences: _maxDartDifferences,
        encode: dart_codec.encodeRgba,
        decode: (hash, premultiplied) =>
            dart_codec.decodeRgba(hash, premultiplied: premultiplied),
      ),
  ];

  test('patterns match the reference generator', () {
    for (final fixture in referenceFixtures) {
      final rgba = patternRgba(fixture.name);
      expect(rgba.length, fixture.width * fixture.height * 4);
      expect(fnv1a(rgba), fixture.inputChecksum, reason: fixture.name);
    }
  });

  for (final codec in codecs) {
    group(codec.name, () {
      for (final fixture in referenceFixtures) {
        test('encodes ${fixture.name} like the reference', () {
          final hash = codec.encode(
            fixture.width,
            fixture.height,
            patternRgba(fixture.name),
          );
          expectHashClose(
            hash,
            base64Decode(fixture.hashBase64),
            maxDifferences: codec.maxHashDifferences,
          );
        });

        test('decodes ${fixture.name} like the reference', () {
          final decoded = codec.decode(base64Decode(fixture.hashBase64), false);
          expect(decoded.width, fixture.decodedWidth);
          expect(decoded.height, fixture.decodedHeight);
          expectBytesClose(decoded.rgba, base64Decode(fixture.decodedBase64));
        });

        test('decodes ${fixture.name} premultiplied', () {
          final hash = base64Decode(fixture.hashBase64);
          final expected = codec.decode(hash, false).rgba;
          premultiply(expected);
          expect(codec.decode(hash, true).rgba, expected);
        });
      }
    });
  }

  group('ThumbHash', () {
    for (final fixture in referenceFixtures) {
      test('inspects ${fixture.name} like the reference', () {
        final hash = ThumbHash.fromBase64(fixture.hashBase64);
        expect(hash.aspectRatio, closeTo(fixture.aspectRatio, 1e-6));

        final color = hash.averageColor;
        final (r, g, b, a) = fixture.averageRgba;
        expect(color.r, closeTo(r, 1e-6));
        expect(color.g, closeTo(g, 1e-6));
        expect(color.b, closeTo(b, 1e-6));
        expect(color.a, closeTo(a, 1e-6));
        expect(hash.hasAlpha, a < 1);
      });
    }

    test('parses base64 with or without padding, URL safe or not', () {
      final hash = ThumbHash.fromBase64('k0oGLQaSVsN0BVhX2oq2Z5SQUQcZ');
      final alpha = ThumbHash.fromBase64(referenceFixtures[3].hashBase64);
      expect(alpha.toBase64(), endsWith('=='));
      expect(ThumbHash.fromBase64(alpha.toBase64().replaceAll('=', '')), alpha);
      expect(
        ThumbHash.fromBase64(base64Url.encode(alpha.bytes).replaceAll('=', '')),
        alpha,
      );
      expect(ThumbHash.fromBase64(hash.toBase64()), hash);
    });

    test('compares by value and drops trailing bytes', () {
      final bytes = base64Decode(referenceFixtures.first.hashBase64);
      final hash = ThumbHash.fromBytes(bytes);
      final padded = ThumbHash.fromBytes([...bytes, 1, 2, 3]);
      expect(padded, hash);
      expect(padded.hashCode, hash.hashCode);
      expect(padded.bytes, bytes);
      expect(
        hash,
        isNot(ThumbHash.fromBase64(referenceFixtures[1].hashBase64)),
      );
      expect(
        hash.toString(),
        'ThumbHash(${referenceFixtures.first.hashBase64})',
      );
    });

    test('is immutable', () {
      final bytes = base64Decode(referenceFixtures.first.hashBase64);
      final hash = ThumbHash.fromBytes(bytes);
      bytes[0] ^= 0xFF;
      expect(hash.bytes[0], isNot(bytes[0]));
      expect(() => hash.bytes[0] = 0, throwsUnsupportedError);
    });

    test('decodes at the reference size', () {
      for (final fixture in referenceFixtures) {
        final pixels = ThumbHash.fromBase64(fixture.hashBase64).toPixels();
        expect(pixels.width, fixture.decodedWidth);
        expect(pixels.height, fixture.decodedHeight);
        expect(pixels.premultiplied, isFalse);
        expect(pixels.rgba.length, pixels.width * pixels.height * 4);
      }
    });

    test('round trips through encoding', () {
      for (final fixture in referenceFixtures) {
        final hash = ThumbHash.fromBase64(fixture.hashBase64);
        final pixels = hash.toPixels();
        final reencoded = ThumbHash.encodeRgba(
          pixels.width,
          pixels.height,
          pixels.rgba,
        );
        expect(reencoded.aspectRatio, hash.aspectRatio, reason: fixture.name);
      }
    });

    test('hashes are at most maxLength bytes long', () {
      for (final fixture in referenceFixtures) {
        final hash = ThumbHash.encodeRgba(
          fixture.width,
          fixture.height,
          patternRgba(fixture.name),
        );
        expect(hash.bytes.length, lessThanOrEqualTo(ThumbHash.maxLength));
      }
    });

    test('accepts views into larger buffers', () {
      final fixture = referenceFixtures.first;
      final rgba = patternRgba(fixture.name);
      final buffer = Uint8List(rgba.length + 16)..setAll(8, rgba);
      expect(
        ThumbHash.encodeRgba(
          fixture.width,
          fixture.height,
          Uint8List.sublistView(buffer, 8, 8 + rgba.length),
        ),
        ThumbHash.encodeRgba(fixture.width, fixture.height, rgba),
      );
    });

    test('rejects invalid images', () {
      expect(() => ThumbHash.encodeRgba(0, 1, Uint8List(0)), throwsRangeError);
      expect(
        () => ThumbHash.encodeRgba(101, 1, Uint8List(101 * 4)),
        throwsRangeError,
      );
      expect(
        () => ThumbHash.encodeRgba(1, 101, Uint8List(101 * 4)),
        throwsRangeError,
      );
      expect(
        () => ThumbHash.encodeRgba(2, 2, Uint8List(15)),
        throwsArgumentError,
      );
    });

    test('rejects invalid hashes', () {
      final valid = base64Decode(referenceFixtures.first.hashBase64);
      final invalid = <String, List<int>>{
        'empty': [],
        'too short': [0, 0, 0, 7],
        'truncated': valid.sublist(0, valid.length - 1),
        'zero luminance components': Uint8List.fromList(valid)..[3] &= ~7,
        'truncated alpha': [0, 0, 0x80, 3, 0],
      };
      for (final MapEntry(key: name, value: bytes) in invalid.entries) {
        expect(ThumbHash.isValid(bytes), isFalse, reason: name);
        expect(
          () => ThumbHash.fromBytes(bytes),
          throwsFormatException,
          reason: name,
        );
      }
      expect(ThumbHash.isValid(valid), isTrue);
      expect(() => ThumbHash.fromBase64('not base64!'), throwsFormatException);
    });
  });
}
