// ignore_for_file: type=lint

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: unused_import, unused_element, deprecated_member_use_from_same_package
import 'dart:ffi' as ffi;

/// Decodes a ThumbHash to an RGBA image of an arbitrary size.
///
/// The reference implementation renders placeholders whose larger side is
/// 32px, see `thumbhash_decoded_size`. `width` and `height` must be in range
/// [1, THUMBHASH_MAX_DECODE_SIZE] and `rgba` must have room for
/// `width * height * 4` bytes. Unless `flags` contains
/// THUMBHASH_DECODE_PREMULTIPLIED, RGB is not premultiplied by A.
///
/// Returns 0 on success, or a negative error code.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<ffi.Uint8>,
    ffi.Int32,
    ffi.Int32,
    ffi.Int32,
    ffi.Uint32,
    ffi.Pointer<ffi.Uint8>,
  )
>(isLeaf: true)
external int thumbhash_decode(
  ffi.Pointer<ffi.Uint8> hash,
  int hash_length,
  int width,
  int height,
  int flags,
  ffi.Pointer<ffi.Uint8> rgba,
);

/// Computes the size of the placeholder rendered by the reference
/// implementation, based on the approximate aspect ratio stored in the hash.
///
/// Returns 0 on success, or a negative error code.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<ffi.Uint8>,
    ffi.Int32,
    ffi.Pointer<ffi.Int32>,
    ffi.Pointer<ffi.Int32>,
  )
>(isLeaf: true)
external int thumbhash_decoded_size(
  ffi.Pointer<ffi.Uint8> hash,
  int hash_length,
  ffi.Pointer<ffi.Int32> width,
  ffi.Pointer<ffi.Int32> height,
);

/// Encodes an RGBA image to a ThumbHash. RGB must not be premultiplied by A.
///
/// `width` and `height` must be in range [1, THUMBHASH_MAX_ENCODE_SIZE].
/// `rgba` holds the pixels row-by-row and must have `width * height * 4`
/// bytes. `hash` must have room for THUMBHASH_MAX_HASH_LENGTH bytes.
///
/// Returns the number of bytes written to `hash`, or a negative error code.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Int32,
    ffi.Int32,
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Uint8>,
  )
>(isLeaf: true)
external int thumbhash_encode(
  int width,
  int height,
  ffi.Pointer<ffi.Uint8> rgba,
  ffi.Pointer<ffi.Uint8> hash,
);

const int THUMBHASH_DECODE_PREMULTIPLIED = 1;

const int THUMBHASH_ERROR_INVALID_ARGUMENT = -1;

const int THUMBHASH_ERROR_INVALID_HASH = -2;

const int THUMBHASH_ERROR_OUT_OF_MEMORY = -3;

const int THUMBHASH_MAX_DECODE_SIZE = 4096;

const int THUMBHASH_MAX_ENCODE_SIZE = 100;

const int THUMBHASH_MAX_HASH_LENGTH = 25;
