//! Generates `test/src/reference_fixtures.dart` using the upstream Rust
//! implementation of ThumbHash (https://github.com/evanw/thumbhash).
//!
//! Run from the repository root:
//!
//! ```sh
//! cargo run --release --manifest-path tool/reference_generator/Cargo.toml \
//!   > test/src/reference_fixtures.dart && dart format test/src
//! ```
//!
//! The synthetic patterns below must stay in sync with
//! `test/src/patterns.dart`. Each fixture stores an FNV-1a checksum of its
//! input pixels, so the tests detect if the two generators ever diverge.

use base64::{engine::general_purpose::STANDARD, Engine};
use std::fmt::Write;

type Pattern = (&'static str, usize, usize, Vec<u8>);

fn generate(w: usize, h: usize, f: impl Fn(usize, usize) -> [u8; 4]) -> Vec<u8> {
    let mut rgba = Vec::with_capacity(w * h * 4);
    for y in 0..h {
        for x in 0..w {
            rgba.extend_from_slice(&f(x, y));
        }
    }
    rgba
}

fn noise(w: usize, h: usize, seed: u32, with_alpha: bool) -> Vec<u8> {
    let mut state = seed;
    let mut next = || {
        state = state.wrapping_mul(1103515245).wrapping_add(12345);
        ((state >> 16) & 255) as u8
    };
    let mut rgba = Vec::with_capacity(w * h * 4);
    for _ in 0..w * h {
        let r = next();
        let g = next();
        let b = next();
        let a = if with_alpha { next() } else { 255 };
        rgba.extend_from_slice(&[r, g, b, a]);
    }
    rgba
}

fn patterns() -> Vec<Pattern> {
    vec![
        ("gradient", 32, 32, generate(32, 32, |x, y| {
            [(x * 255 / 31) as u8, (y * 255 / 31) as u8, 128, 255]
        })),
        ("landscape", 100, 60, generate(100, 60, |x, y| {
            [((x * y) % 256) as u8, ((x + 3 * y) % 256) as u8, (255 - 2 * x) as u8, 255]
        })),
        ("portrait", 40, 100, generate(40, 100, |x, y| {
            [(255 - 2 * y) as u8, ((x * 7) % 256) as u8, ((x * y / 3) % 256) as u8, 255]
        })),
        ("circle_alpha", 64, 64, generate(64, 64, |x, y| {
            let dx = 2 * x as i64 + 1 - 64;
            let dy = 2 * y as i64 + 1 - 64;
            let d2 = dx * dx + dy * dy;
            let a = if d2 < 48 * 48 { 255 } else if d2 < 56 * 56 { 128 } else { 0 };
            [200, ((x * 4) % 256) as u8, ((y * 4) % 256) as u8, a]
        })),
        ("alpha_gradient", 50, 80, generate(50, 80, |x, y| {
            [(x * 5) as u8, 100, (y * 3) as u8, (y * 255 / 79) as u8]
        })),
        ("noise", 100, 100, noise(100, 100, 42, false)),
        ("noise_alpha", 37, 53, noise(37, 53, 7, true)),
        ("single_pixel", 1, 1, vec![12, 34, 56, 255]),
        ("transparent", 10, 10, vec![0; 10 * 10 * 4]),
        ("solid", 20, 20, generate(20, 20, |_, _| [10, 200, 90, 255])),
        ("wide", 100, 1, generate(100, 1, |x, _| {
            [(x * 2) as u8, (255 - x * 2) as u8, x as u8, 255]
        })),
        ("tall", 1, 100, generate(1, 100, |_, y| {
            [y as u8, (y * 2) as u8, (255 - y * 2) as u8, 255]
        })),
    ]
}

fn flower() -> Pattern {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../../test/assets/flower.jpg");
    let image = image::open(path).expect("cannot open flower.jpg").to_rgba8();
    let (w, h) = (image.width() as usize, image.height() as usize);
    let scale = 100.0 / w.max(h) as f64;
    let (tw, th) = (
        ((w as f64 * scale).round() as u32).max(1),
        ((h as f64 * scale).round() as u32).max(1),
    );
    let resized = image::imageops::resize(&image, tw, th, image::imageops::FilterType::Triangle);
    ("flower", tw as usize, th as usize, resized.into_raw())
}

fn fnv1a(bytes: &[u8]) -> u32 {
    let mut hash: u32 = 0x811c9dc5;
    for &b in bytes {
        hash ^= b as u32;
        hash = hash.wrapping_mul(0x01000193);
    }
    hash
}

fn main() {
    let mut out = String::new();
    writeln!(out, "// GENERATED FILE, DO NOT EDIT.").unwrap();
    writeln!(out, "//").unwrap();
    writeln!(out, "// Generated by `tool/reference_generator` using the upstream Rust").unwrap();
    writeln!(out, "// implementation of ThumbHash.").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "import 'reference_fixture.dart';").unwrap();
    writeln!(out).unwrap();

    let (_, fw, fh, frgba) = flower();
    writeln!(out, "const flowerWidth = {fw};").unwrap();
    writeln!(out, "const flowerHeight = {fh};").unwrap();
    writeln!(out, "const flowerRgbaBase64 = '{}';", STANDARD.encode(&frgba)).unwrap();
    writeln!(out).unwrap();

    writeln!(out, "const referenceFixtures = <ReferenceFixture>[").unwrap();
    let mut all = patterns();
    all.push(flower());
    for (name, w, h, rgba) in all {
        let hash = thumbhash::rgba_to_thumb_hash(w, h, &rgba);
        let (dw, dh, decoded) = thumbhash::thumb_hash_to_rgba(&hash).unwrap();
        let (r, g, b, a) = thumbhash::thumb_hash_to_average_rgba(&hash).unwrap();
        let ratio = thumbhash::thumb_hash_to_approximate_aspect_ratio(&hash).unwrap();
        writeln!(out, "  ReferenceFixture(").unwrap();
        writeln!(out, "    name: '{name}',").unwrap();
        writeln!(out, "    width: {w},").unwrap();
        writeln!(out, "    height: {h},").unwrap();
        writeln!(out, "    inputChecksum: 0x{:08x},", fnv1a(&rgba)).unwrap();
        writeln!(out, "    hashBase64: '{}',", STANDARD.encode(&hash)).unwrap();
        writeln!(out, "    decodedWidth: {dw},").unwrap();
        writeln!(out, "    decodedHeight: {dh},").unwrap();
        writeln!(out, "    decodedBase64: '{}',", STANDARD.encode(&decoded)).unwrap();
        writeln!(out, "    averageRgba: ({r:?}, {g:?}, {b:?}, {a:?}),").unwrap();
        writeln!(out, "    aspectRatio: {ratio:?},").unwrap();
        writeln!(out, "  ),").unwrap();
    }
    writeln!(out, "];").unwrap();
    print!("{out}");
}
