// C ABI of the thumbhash crate (https://github.com/evanw/thumbhash).

#ifndef THUMBHASH_FFI_H_
#define THUMBHASH_FFI_H_

// Generated by cbindgen from src/lib.rs, do not edit.

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

// The maximum number of bytes in a ThumbHash.
#define THUMBHASH_MAX_HASH_LENGTH 25

// The maximum width and height of an image that can be encoded.
#define THUMBHASH_MAX_ENCODE_SIZE 100

// The maximum number of bytes of a decoded image (at most 32x32 RGBA).
#define THUMBHASH_MAX_DECODED_LENGTH ((32 * 32) * 4)

// The call succeeded.
#define THUMBHASH_OK 0

// One of the arguments is out of range, or a pointer is null.
#define THUMBHASH_ERROR_INVALID_ARGUMENT -1

// The hash is malformed or too short.
#define THUMBHASH_ERROR_INVALID_HASH -2

// The implementation panicked.
#define THUMBHASH_ERROR_PANIC -3

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Encodes an RGBA image to a ThumbHash. RGB must not be premultiplied by A.
//
// `width` and `height` must be in range [1, THUMBHASH_MAX_ENCODE_SIZE] and
// `rgba` must hold exactly `width * height * 4` bytes, row by row. `hash`
// must have room for THUMBHASH_MAX_HASH_LENGTH bytes.
//
// Returns the number of bytes written to `hash`, or a negative error code.
//
// # Safety
//
// `rgba` must point to `rgba_length` readable bytes and `hash` to
// THUMBHASH_MAX_HASH_LENGTH writable bytes.
int32_t thumbhash_encode(uint32_t width,
                         uint32_t height,
                         const uint8_t *rgba,
                         size_t rgba_length,
                         uint8_t *hash);

// Decodes a ThumbHash to an RGBA image, whose larger side is 32 pixels.
//
// Writes the pixels to `rgba`, row by row, and the size of the image to
// `size` (width, then height). RGB is premultiplied by A if `premultiplied`
// is true.
//
// Returns THUMBHASH_OK, or a negative error code.
//
// # Safety
//
// `hash` must point to `hash_length` readable bytes, `rgba` to
// THUMBHASH_MAX_DECODED_LENGTH writable bytes and `size` to 2 writable
// integers.
int32_t thumbhash_decode(const uint8_t *hash,
                         size_t hash_length,
                         bool premultiplied,
                         uint8_t *rgba,
                         uint32_t *size);

// Extracts the average color from a ThumbHash.
//
// Writes red, green, blue and alpha, each in range [0, 1], to `rgba`. RGB is
// not premultiplied by A.
//
// Returns THUMBHASH_OK, or a negative error code.
//
// # Safety
//
// `hash` must point to `hash_length` readable bytes and `rgba` to 4
// writable floats.
int32_t thumbhash_average_rgba(const uint8_t *hash, size_t hash_length, float *rgba);

// Extracts the approximate aspect ratio (width / height) of the original
// image.
//
// Returns the ratio, or a negative error code.
//
// # Safety
//
// `hash` must point to `hash_length` readable bytes.
float thumbhash_approximate_aspect_ratio(const uint8_t *hash, size_t hash_length);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* THUMBHASH_FFI_H_ */
